# Generated by Django 5.1.15 on 2026-09-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_otomax_net_pair_note'),
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='otomax_entries',
            field=models.ManyToManyField(blank=True, help_text='Semua baris Otomax dalam grup untuk match AGGREGATE (QRIS multi-baris). otomax_entry di atas tetap menunjuk baris utama untuk tampilan.', related_name='aggregate_matches', to='ingest.otomaxentry'),
        ),
    ]
