# Generated by Django 5.1.15 on 2026-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_otomax_net_pair_note'),
        ('recon', '0004_mark_unreviewed_fuzzy_as_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bank_mutations',
            field=models.ManyToManyField(blank=True, help_text='Semua mutasi bank dalam gabungan manual BEBERAPA mutasi <-> 1 entri Otomax (mis. satu Tartun QR Bulk menutup settlement 2 outlet QRIS). bank_mutation di atas tetap menunjuk mutasi utama untuk tampilan.', related_name='aggregate_bank_matches', to='ingest.bankmutation'),
        ),
    ]
