# Generated by Django 5.1.15 on 2026-09-20 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_month_start_day', models.PositiveSmallIntegerField(default=1, help_text='Tanggal mulai siklus bulan bisnis (1-31) untuk expand Alarm SLA. 1 = kalender biasa. Contoh: 29 -> siklus tgl 29 s/d 28.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Aplikasi',
                'verbose_name_plural': 'Pengaturan Aplikasi',
            },
        ),
    ]
