# Generated by Django 5.1.15 on 2026-10-01 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_app_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='bca_date_tolerance_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari maju (H+max) untuk BCA.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='bca_date_tolerance_min',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari mundur (H-min) untuk BCA.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='bri_date_tolerance_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari maju (H+max) untuk BRI.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='bri_date_tolerance_min',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari mundur (H-min) untuk BRI.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mandiri_date_tolerance_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari maju (H+max) untuk Mandiri.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mandiri_date_tolerance_min',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari mundur (H-min) untuk Mandiri.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='merchant_bca_date_tolerance_max',
            field=models.PositiveSmallIntegerField(default=2, help_text='Toleransi hari maju (H+max) untuk Merchant BCA.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='merchant_bca_date_tolerance_min',
            field=models.PositiveSmallIntegerField(default=1, help_text='Toleransi hari mundur (H-min) untuk Merchant BCA.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
