# Generated by Django 5.1.15 on 2026-09-14 08:47

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nama atau label aturan', max_length=120)),
                ('keywords', models.CharField(help_text='Kata kunci dalam keterangan (pisahkan koma jika banyak, case-insensitive)', max_length=255)),
                ('target', models.CharField(choices=[('BANK', 'Mutasi Bank'), ('OTOMAX', 'Data Otomax'), ('ALL', 'Semua Data (Bank & Otomax)')], default='BANK', max_length=16)),
                ('channel', models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], default='', help_text='Kosongkan jika berlaku untuk semua channel', max_length=16)),
                ('category', models.CharField(choices=[('BIAYA_ADMIN', 'Biaya Administrasi Bank'), ('TRANSFER_INTERNAL', 'Transfer Internal / Pemindahan Dana'), ('PAJAK_BUNGA', 'Pajak & Bunga'), ('NON_OPERASIONAL', 'Pengeluaran Non-Operasional'), ('LAINNYA', 'Lainnya')], default='BIAYA_ADMIN', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExclusionRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(help_text='Nama atau label aturan', max_length=120)),
                ('keywords', models.CharField(help_text='Kata kunci dalam keterangan (pisahkan koma jika banyak, case-insensitive)', max_length=255)),
                ('target', models.CharField(choices=[('BANK', 'Mutasi Bank'), ('OTOMAX', 'Data Otomax'), ('ALL', 'Semua Data (Bank & Otomax)')], default='BANK', max_length=16)),
                ('channel', models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], default='', help_text='Kosongkan jika berlaku untuk semua channel', max_length=16)),
                ('category', models.CharField(choices=[('BIAYA_ADMIN', 'Biaya Administrasi Bank'), ('TRANSFER_INTERNAL', 'Transfer Internal / Pemindahan Dana'), ('PAJAK_BUNGA', 'Pajak & Bunga'), ('NON_OPERASIONAL', 'Pengeluaran Non-Operasional'), ('LAINNYA', 'Lainnya')], default='BIAYA_ADMIN', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical exclusion rule',
                'verbose_name_plural': 'historical exclusion rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
