# Generated by Django 5.1.15 on 2026-09-08 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], max_length=16)),
                ('book_date', models.DateField()),
                ('source_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('quarantined_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PARSED', 'Parsed'), ('PARTIAL', 'Sebagian (ada baris dikarantina)'), ('FAILED', 'Gagal')], default='PARSED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitIgnored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], max_length=16)),
                ('book_date', models.DateField(db_index=True)),
                ('txn_datetime', models.DateTimeField(blank=True, null=True)),
                ('description_raw', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positif; arah keluar tersirat.', max_digits=15)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='ingest.importbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], db_index=True, max_length=16)),
                ('book_date', models.DateField(db_index=True)),
                ('txn_datetime', models.DateTimeField(blank=True, null=True)),
                ('description_raw', models.TextField()),
                ('ref_normalized', models.TextField(db_index=True)),
                ('ref_core', models.CharField(blank=True, db_index=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('external_ref', models.CharField(blank=True, db_index=True, max_length=40)),
                ('frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Belum cocok'), ('MATCHED', 'Cocok (otomatis)'), ('MANUAL', 'Cocok (manual)'), ('IGNORED', 'Diabaikan')], db_index=True, default='UNMATCHED', max_length=12)),
                ('review_flag', models.CharField(blank=True, max_length=120)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='ingest.importbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['book_date', 'channel', 'match_status'], name='ingest_bank_book_da_5fab06_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtomaxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_date', models.DateField(db_index=True)),
                ('entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('reseller_name_raw', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description_raw', models.TextField()),
                ('category', models.CharField(choices=[('TOPUP_TARTUN', 'Top-up tarik tunai'), ('ADMIN', 'Potongan admin'), ('REVERSAL', 'Reversal'), ('STOR_IN', 'Setoran masuk'), ('STOR_OUT', 'Ambil setoran'), ('DEPOSIT', 'Deposit manual'), ('PAYMENT', 'Pembayaran'), ('OTHER', 'Lain-lain')], db_index=True, default='OTHER', max_length=16)),
                ('channel_hint', models.CharField(blank=True, choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], db_index=True, max_length=16)),
                ('ref_normalized', models.TextField(blank=True, db_index=True)),
                ('ref_core', models.CharField(blank=True, db_index=True, max_length=80)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('match_status', models.CharField(choices=[('UNMATCHED', 'Belum cocok'), ('MATCHED', 'Cocok (otomatis)'), ('MANUAL', 'Cocok (manual)'), ('IGNORED', 'Diabaikan')], db_index=True, default='UNMATCHED', max_length=12)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otomax', to='ingest.importbatch')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otomax_entries', to='catalog.reseller')),
            ],
            options={
                'indexes': [models.Index(fields=['book_date', 'category', 'match_status'], name='ingest_otom_book_da_f60055_idx')],
            },
        ),
    ]
