# Generated by Django 5.1.15 on 2026-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_add_manual_tag_and_tokens'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankmutation',
            new_name='ingest_bank_match_s_778611_idx',
            old_name='ingest_bank_match_tag_idx',
        ),
        migrations.AlterField(
            model_name='bankmutation',
            name='tag_manual',
            field=models.CharField(blank=True, choices=[('admin', 'Biaya Admin'), ('tarik_tunai', 'Tarik Tunai'), ('setor_tunai', 'Setor Tunai'), ('revisi', 'Revisi'), ('lainnya', 'Lainnya')], db_index=True, default='', max_length=20),
        ),
    ]
