# Generated by Django 5.1.15 on 2026-09-14 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_exclusionrule_historicalexclusionrule'),
        ('ingest', '0003_rename_ingest_bank_match_tag_idx_ingest_bank_match_s_778611_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='excluded_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ExcludedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('BRI', 'BRI'), ('BCA', 'BCA'), ('MERCHANT_BCA', 'Merchant BCA (QRIS)'), ('MANDIRI', 'Mandiri'), ('OTOMAX', 'OTOMAX')], db_index=True, max_length=16)),
                ('source_type', models.CharField(choices=[('BANK', 'Bank'), ('OTOMAX', 'Otomax')], default='BANK', max_length=10)),
                ('book_date', models.DateField(db_index=True)),
                ('txn_datetime', models.DateTimeField(blank=True, null=True)),
                ('description_raw', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_transactions', to='ingest.importbatch')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excluded_transactions', to='catalog.exclusionrule')),
            ],
            options={
                'ordering': ['-txn_datetime', '-id'],
                'indexes': [models.Index(fields=['book_date', 'channel'], name='ingest_excl_book_da_bf717a_idx'), models.Index(fields=['source_type', 'book_date'], name='ingest_excl_source__af9e3e_idx')],
            },
        ),
    ]
