# Generated by Django 5.1.15 on 2026-09-17 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_importbatch_excluded_count_excludedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='otomaxentry',
            name='net_pair',
            field=models.ForeignKey(blank=True, help_text='Entri TOPUP_TARTUN/REVERSAL lawan yang saling menetralkan (ref & nominal berlawanan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ingest.otomaxentry'),
        ),
        migrations.AddField(
            model_name='otomaxentry',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
