# Generated by Django 5.1.15 on 2026-10-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_otomax_net_pair_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludedtransaction',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='excludedtransaction',
            name='party_raw',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
